# Generated by Django 5.1.1 on 2024-10-02 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0001_initial'),
        ('materias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='horario',
            field=models.ManyToManyField(blank=True, to='horarios.horario'),
        ),
    ]
