# Generated by Django 5.0.6 on 2024-11-16 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='horarios_por_dia',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
