# Generated by Django 5.1.1 on 2024-10-09 22:30

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0002_alter_materia_horario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='dias_da_semana',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(2, 'Segunda-feira'), (3, 'Terça-feira'), (4, 'Quarta-feira'), (5, 'Quinta-feira'), (6, 'Sexta-feira'), (7, 'Sábado')], max_length=100),
        ),
    ]
