# Generated by Django 5.0.6 on 2024-10-10 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0003_alter_materia_dias_da_semana'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materia',
            name='dias_da_semana',
        ),
        migrations.RemoveField(
            model_name='materia',
            name='horario',
        ),
        migrations.AddField(
            model_name='materia',
            name='horarios_por_dia',
            field=models.JSONField(default=dict),
        ),
    ]
