# Generated by Django 5.0.6 on 2024-10-10 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0004_remove_materia_dias_da_semana_remove_materia_horario_and_more'),
        ('professors', '0005_remove_professor_materias'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='professor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='professors.professor'),
            preserve_default=False,
        ),
    ]
