# Generated by Django 5.0.6 on 2024-10-10 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0005_materia_professor'),
        ('professors', '0005_remove_professor_materias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='professors.professor'),
        ),
    ]
