# Generated by Django 5.0.2 on 2024-09-06 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('max_horas', models.IntegerField()),
                ('horas_atuais', models.IntegerField(default=0)),
            ],
        ),
    ]
