# Generated by Django 5.0.2 on 2024-09-07 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('professors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='cursos',
            field=models.ManyToManyField(related_name='professores', to='courses.course'),
        ),
        migrations.AddField(
            model_name='professor',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='professor',
            name='ra',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
    ]
