# Generated by Django 5.0.2 on 2024-09-23 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0001_initial'),
        ('professors', '0002_professor_cursos_professor_email_professor_ra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='cursos',
        ),
        migrations.AddField(
            model_name='professor',
            name='materias',
            field=models.ManyToManyField(to='materias.materia'),
        ),
    ]
