# Generated by Django 5.0.6 on 2024-10-10 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0004_alter_professor_materias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='materias',
        ),
    ]
