# Generated by Django 5.0.2 on 2024-10-15 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0005_remove_professor_materias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='horas_atuais',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='professor',
            name='max_horas',
            field=models.FloatField(),
        ),
    ]
