# Generated by Django 5.0.2 on 2024-09-23 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('materias', '0001_initial'),
        ('professors', '0003_remove_professor_cursos_professor_materias'),
        ('turmas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='materias',
            field=models.ManyToManyField(to='materias.materia'),
        ),
        migrations.AddField(
            model_name='course',
            name='professor_coordenador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='professors.professor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='turmas',
            field=models.ManyToManyField(to='turmas.turma'),
        ),
        migrations.AlterField(
            model_name='course',
            name='nome',
            field=models.CharField(max_length=150),
        ),
    ]
