# Generated by Django 5.0.6 on 2024-10-22 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('turmas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='turmas',
            field=models.ManyToManyField(blank=True, to='turmas.turma'),
        ),
    ]
