# Generated by Django 5.1.1 on 2024-10-09 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_materias_and_more'),
        ('materias_modelo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='materias',
            field=models.ManyToManyField(blank=True, to='materias_modelo.materia'),
        ),
    ]
