# Generated by Django 5.0.6 on 2024-10-10 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0005_materia_professor'),
        ('turmas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='materias_copy',
            field=models.ManyToManyField(blank=True, to='materias.materia'),
        ),
    ]
